README:
	julia --project=. build.jl readme.jl
	cp readme.md ../README.md

nhanes:
	julia --project=. build.jl nhanes.jl

ozone:
	julia --project=. build.jl ozone.jl

ames:
	julia --project=. build.jl ames.jl
